name: CI

on:
  push:
    branches:
    - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
  
permissions:
  actions: write
  contents: read

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    env:
      PLOTTING_BACKEND: github
    strategy:
      fail-fast: false
      matrix:
        version: ['1.9.3']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@main
      - uses: julia-actions/setup-julia@master
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@main
      - uses: julia-actions/julia-buildpkg@main
      - uses: julia-actions/julia-runtest@main
      - uses: actions/upload-artifact@main
        with:
          name: data-output-${{ matrix.os }}
          path: ./data-output


