name: Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: julia-actions/setup-julia@master
        with:
          version: 1.9.3
      - uses: julia-actions/cache@main
      - uses: julia-actions/julia-buildpkg@main
        with:
          project: docs
      - name: Build and deploy docs
        run: julia --project=docs docs/make.jl
