name: Julia CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [1.9.3]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: |
          julia --project -e 'using Pkg; Pkg.instantiate()'
      - name: Test
        #run: julia --project=docs/ -e 'using Pkg; Pkg.test()'
        run: julia --project -e 'using Pkg; Pkg.test()'
